site_name: FAgents Docs

nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search

  - mkdocstrings:
      handlers:
        python:
          paths:
            - src

  - mkdocs-autoapi:
      autoapi_dir: src